# Generated by Django 3.2.6 on 2021-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_new',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='create_new',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='create_new',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='create_new',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
